# Stage 1: Build the React Application

FROM node:20 AS build

ARG ROLE=PATIENT

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV VITE_APP_ROLE=$ROLE

RUN npm run build

# Stage 2: Serve via Nginx

FROM nginx:1.25-alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
