# ==========================================
# Enterprise Consultation Platform Default Configurations
# ==========================================

# Active spring profile. Defaults to local (with local MySQL connector settings)
spring.profiles.active=local

# Server Port
server.port=8080
